local o = vim.opt
local g = vim.g

-- options
o.backup = false -- creates a backup file
o.clipboard = "unnamedplus" -- Connection to the system clipboard
o.completeopt = { "menuone", "noselect" } -- options for insert mode completion
o.cursorline = true -- Highlight the current line
o.expandtab = true -- convert tabs to spaces
o.fileencoding = "utf-8" -- File content encoding for the buffer
o.fillchars = { eob = " " } -- Disable `~` on nonexistent lines
o.history = 100 -- Number of commands to remember in a history table
o.ignorecase = true -- Case insensitive searching
o.laststatus = 3 -- globalstatus
o.lazyredraw = true -- lazily redraw screen
o.mouse = "a" -- Enable mouse support
o.number = true -- Show numberline
o.pumheight = 10 -- Height of the pop up menu
o.relativenumber = true -- Show relative numberline
o.sidescrolloff = 8 -- Number of columns to keep at the sides of the cursor
o.scrolloff = 8 -- Number of lines to keep above and below the cursor
o.tabstop = 4 -- Number of space in a tab
o.shiftwidth = 4 -- Number of space inserted for indentation
o.softtabstop = 0
o.preserveindent = false -- Preserve indent structure as much as possible
o.showmode = false -- Disable showing modes in command line
o.smartcase = true -- Case sensitive searching
o.autoindent = true
o.smartindent = true -- make indenting smarter again
o.signcolumn = "yes" -- Always show the sign column
o.splitbelow = true -- Splitting a new window below the current one
o.splitright = true -- Splitting a new window at the right of the current one
o.swapfile = false -- Disable use of swapfile for the buffer
o.termguicolors = true -- Enable 24-bit RGB color in the TUI
o.timeout = true
o.timeoutlen = 300 -- Length of time to wait for a mapped sequence
o.undofile = true -- Enable persistent undo
o.updatetime = 200 -- Length of time to wait before triggering the plugin
o.wrap = true -- Wrap lines longer than the width of window
o.autoread = true
o.hlsearch = false
o.incsearch = true
o.colorcolumn = "80"
o.statuscolumn =
	"%=%l%s%#FoldColumn#%{foldlevel(v:lnum) > foldlevel(v:lnum - 1) ? (foldclosed(v:lnum) == -1 ? \" \" : \" \") : \"  \" }%*"
o.foldenable = true
o.foldcolumn = "1"
o.foldlevel = 99
o.foldlevelstart = 99

-- Global
g.mapleader = " "
g.codeium_disable_bindings = 1
g.better_escape_shortcut = "qq"
g.better_escape_interval = 500
g.highlighturl_enabled = true -- highlight URLs by default
g.zipPlugin = false -- disable zip
g.load_black = false -- disable black
g.loaded_2html_plugin = true -- disable 2html
g.loaded_getscript = true -- disable getscript
g.loaded_getscriptPlugin = true -- disable getscript
g.loaded_gzip = true -- disable gzip
g.loaded_logipat = true -- disable logipat
g.loaded_matchit = true -- disable matchit
g.loaded_netrwFileHandlers = true -- disable netrw
g.loaded_netrwPlugin = true -- disable netrw
g.loaded_netrwSettngs = true -- disable netrw
g.loaded_remote_plugins = true -- disable remote plugins
g.loaded_tar = true -- disable tar
g.loaded_tarPlugin = true -- disable tar
g.loaded_zip = true -- disable zip
g.loaded_zipPlugin = true -- disable zip
g.loaded_vimball = true -- disable vimball
g.loaded_vimballPlugin = true -- disable vimball
g.loaded_vimballPlugin = true -- disable vimball
g.loaded_vimballPlugin = true -- disable vimball
g.loaded_vimballPlugin = true -- disable vimball
g.loaded_vimballPlugin = true -- disable vimball
